name: AddressCalculator
version: '1.0'
main: me.emmatoocold.addressCalculator.addressCalculator
api-version: '1.21'
commands:
  getaddress:
    description: Calculates plot address.
    aliases: [ address ]

  getaddressmap:
    description: Grabs address map.
    aliases: [ addressmap ]
